### ISSUE TITLE
[PE-D][Tester A] The hyperlinks under table of content does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-4/tp#266]
![Screenshot 2023-03-31 141756.png](https://raw.githubusercontent.com/CShuwen/ped/main/files/daecf9ea-cec0-45f5-a462-ba85de835b60.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: CShuwen/ped#1

**Comment by SFCoding123** [comment]
Issue taken note
