### ISSUE TITLE
[PE-D][Tester D] Storage not cleared when first starting up

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-4/tp#273]
When I first start up the app, there are already some entries present. This could cause some inconvenience to new users because they would need to clear the list, which may not be user-friendly.

![screenshot2.png](https://raw.githubusercontent.com/Jun-How/ped/main/files/9a33c524-5d54-41c8-bd65-596348d2f60b.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Jun-How/ped#2

**Comment by SFCoding123** [comment]
Change the User Guide to the statement that it starts with the default patient list not empty.
