### ISSUE TITLE
[PE-D][Tester A] No command to view patient

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-4/tp#298]
Based on the requirement that this should be an application focusing on CLI, I feel that it might be good to include a command 'view PATIENT_INDEX' to view patient by their index. If not the patient can only be viewed by mouse click.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: CShuwen/ped#8

**Comment by SFCoding123** [comment]
include in the user guide show {index}

**Comment by WeideTeo** [comment]
Noted

**Comment by WeideTeo** [comment]
Added, fixed
