### ISSUE TITLE
[PE-D][Tester D] The view command is not behaving as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-4/tp#300]
I have a pdf entry for the first patient, but when I type in "view 1 1", I am unable to view and got the error message "The File index provided is invalid". Perhaps there is an indexing error occurring here. Although I could still view the pdf document by clicking on "view" in the GUI, this may still hinder users, especially since the app revolves around a CLI.

![image.png](https://raw.githubusercontent.com/Jun-How/ped/main/files/daddde0e-f598-470f-9c7d-e8f22be11f3e.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Jun-How/ped#7

**Comment by SFCoding123** [comment]
Similar issues noted
