### ISSUE TITLE
[PE-D][Tester D] Unable to delete file using CLI

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-4/tp#303]
I have a pdf document uploaded for the first patient, but when I tried to delete the file by typing "deleteFile 1 1", which I believe is the correct format according to the UG, a confirmation pop-up appears and I click "OK", but afterwards an error message "Unknown command" pops up and the file was not deleted. This might be inconvenient for users who are using the CLI.

![image.png](https://raw.githubusercontent.com/Jun-How/ped/main/files/4d23b841-2cbb-4ae0-8302-8a6a42c19886.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Jun-How/ped#10

**Comment by SFCoding123** [comment]
Wrong UG written
