### ISSUE TITLE
[PE-D][Tester E] Incomplete documentation for markApp

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-4/tp#310]
User guide states that there is a way to mark an appointment using the button method but did not include the steps to do it.

![image.png](https://raw.githubusercontent.com/venuslimm/ped/main/files/cd4e5860-48ad-429b-9eb9-acfe8cf4f03f.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: venuslimm/ped#11

**Comment by SFCoding123** [comment]
Remove the Button method
