### ISSUE TITLE
[PE-D][Tester E] No button to mark appointment as done

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-4/tp#311]
User guide states that there is a way to mark an appointment as done using buttons but there is no buttons to do so on MediMate.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: venuslimm/ped#12

**Comment by SFCoding123** [comment]
No button intended
Mark using command

**Comment by SFCoding123** [comment]
Change user guide
