### ISSUE TITLE
[PE-D][Tester E] Valid number of days of unfit but treated as invalid for create command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-4/tp#313]
Any positive integers are considered valid number of days of unfit as stated on the user guide but `100` is considered an invalid input.

![image.png](https://raw.githubusercontent.com/venuslimm/ped/main/files/f264f354-5193-4b36-9d3d-518924a83e2c.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: venuslimm/ped#14

**Comment by SFCoding123** [comment]
Change the User guide to 60 days

**Comment by WeideTeo** [comment]
Added
