### ISSUE TITLE
[PE-D][Tester E] Unable to upload bmp format file as medical file

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-4/tp#317]
After selecting a bmp file to be uploaded, the list of medical files for the specific patient is not updated with the newly added file.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: venuslimm/ped#18

**Comment by SFCoding123** [comment]
User guide add only accept pdf jpg jpeg and png file

**Comment by WeideTeo** [comment]
Fix
