### ISSUE TITLE
[PE-D][Tester E] deleteFile is an unknown command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-4/tp#321]
User guide includes `deleteFile` as a feature but this command cannot be executed successfully on the application.

![image.png](https://raw.githubusercontent.com/venuslimm/ped/main/files/cc756ce5-b10c-4a9e-9948-24c98cd0e872.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: venuslimm/ped#22

**Comment by SFCoding123** [comment]
Should be deletefile

**Comment by WeideTeo** [comment]
Fix
